# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  # ────────────── JavaScript / Node (npm) ──────────────
  - package-ecosystem: "npm"
    directory: "/"                # where package.json lives
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels: ["dependencies", "npm"]
    rebase-strategy: "auto"
    commit-message:
      prefix: "npm"
      include: "scope"
    groups:
      npm-minor-patch:
        applies-to: "version-updates"
        update-types: ["minor", "patch"]

  # ────────────── Python (pip / requirements.txt) ──────────────
  - package-ecosystem: "pip"
    directory: "/"                # where requirements.txt lives
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:10"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels: ["dependencies", "python"]
    rebase-strategy: "auto"
    commit-message:
      prefix: "pip"
      include: "scope"
    # allow both direct & transitive bumps (default, but explicit here)
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      pip-minor-patch:
        applies-to: "version-updates"
        update-types: ["minor", "patch"]

  # ────────────── GitHub Actions (workflows) ──────────────
  - package-ecosystem: "github-actions"
    directory: "/"                # .github/workflows
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:20"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]
    rebase-strategy: "auto"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      gha-minor-patch:
        applies-to: "version-updates"
        update-types: ["minor", "patch"]

---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
      timezone: "UTC"
    labels: ["dependencies", "npm", "automerge"]
    groups:
      npm-all:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
      timezone: "UTC"
    labels: ["ci", "automerge"]
    groups:
      gha-all:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "03:00"
      timezone: "UTC"
    labels: ["dependencies", "python", "automerge"]
    groups:
      pip-all:
        patterns: ["*"]
        update-types: ["major", "minor", "patch"]
---