module.exports = [
    {
        ignores: [
            '.claude/**',
            'node_modules/**',
            'coverage/**',
            'assets/**',
            'js/sketch.js',
            'js/vendor/**',
            'docs/reference/**',
            'venv/**',
            'dist/**',
            'data/**',
            '**/*.min.js',
            '.mypy_cache/**',
            '.pytest_cache/**',
            '.ruff_cache/**',
        ],
    },
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                fetch: 'readonly',
                performance: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                Image: 'readonly',
                CustomEvent: 'readonly',
                Event: 'readonly',
                KeyboardEvent: 'readonly',
                Element: 'readonly',
                HTMLCanvasElement: 'readonly',
                MouseEvent: 'readonly',
                TouchEvent: 'readonly',
                process: 'readonly',
                URL: 'readonly',
                Chart: 'readonly',
                ChartDataLabels: 'readonly',
                d3: 'readonly',
                CalHeatmap: 'readonly',
            },
        },
        rules: {
            'no-undef': 'error',
            'no-unused-vars': ['warn', { args: 'after-used', ignoreRestSiblings: true }],
            'no-unreachable': 'error',
            'no-constant-binary-expression': 'error',
            eqeqeq: ['warn', 'always', { null: 'ignore' }],
            'no-var': 'warn',
            'prefer-const': ['warn', { destructuring: 'all' }],
            'no-useless-return': 'warn',
            'no-extra-boolean-cast': 'warn',
            'no-multi-assign': 'warn',
            'no-lonely-if': 'warn',
            'no-else-return': 'warn',
            curly: ['error', 'all'],
            'no-trailing-spaces': 'warn',
            'eol-last': ['warn', 'always'],
            semi: ['warn', 'always'],
            quotes: ['warn', 'single', { avoidEscape: true }],
            'keyword-spacing': ['warn', { before: true, after: true }],
            'space-before-blocks': ['warn', 'always'],
            'comma-spacing': ['warn', { before: false, after: true }],
            'object-curly-spacing': ['warn', 'always'],
            'arrow-spacing': ['warn', { before: true, after: true }],
            'no-multi-spaces': ['warn'],
            'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
            'no-multiple-empty-lines': ['warn', { max: 1, maxEOF: 1 }],
            'no-console': 'warn',
        },
    },
    {
        // Timezone landmine (docs/testing-notes.md § Timezone): extracting a
        // day key via toISOString() from a locally-parsed Date lands on the
        // previous calendar day in UTC+ zones (prod browsers run UTC+8, the
        // test suite runs UTC and can't catch it). Use toLocalIsoDate() from
        // js/utils/date.js, or eslint-disable with a comment proving the Date
        // is UTC-domain (built via Date.UTC / parsed from a bare ISO string).
        files: ['js/**/*.js'],
        rules: {
            'no-restricted-syntax': [
                'error',
                {
                    selector:
                        "CallExpression[callee.property.name='split'][callee.object.callee.property.name='toISOString']",
                    message:
                        'toISOString() day keys shift a day in UTC+ timezones. Use toLocalIsoDate() from js/utils/date.js for local-calendar dates, or eslint-disable this line with a comment proving the Date is UTC-domain.',
                },
            ],
        },
    },
    {
        files: ['sw.js'],
        languageOptions: {
            globals: {
                self: 'readonly',
                caches: 'readonly',
                clients: 'readonly',
                Cache: 'readonly',
                CacheStorage: 'readonly',
                Request: 'readonly',
                Response: 'readonly',
                URL: 'readonly',
                location: 'readonly',
            },
        },
    },
    {
        files: ['tests/js/**/*.js'],
        languageOptions: {
            globals: {
                require: 'readonly',
                module: 'readonly',
                global: 'readonly',
                jest: 'readonly',
                describe: 'readonly',
                it: 'readonly',
                test: 'readonly',
                expect: 'readonly',
                beforeEach: 'readonly',
                afterEach: 'readonly',
                beforeAll: 'readonly',
                afterAll: 'readonly',
                window: 'readonly',
                document: 'readonly',
                performance: 'readonly',
                requestAnimationFrame: 'readonly',
                Buffer: 'readonly',
                Request: 'readonly',
            },
        },
        rules: {
            'no-console': 'off',
        },
    },
    {
        files: ['worker/**/*.js'],
        languageOptions: {
            globals: {
                Request: 'readonly',
                Response: 'readonly',
                URL: 'readonly',
                AbortSignal: 'readonly',
                AbortController: 'readonly',
                btoa: 'readonly',
                fetch: 'readonly',
                console: 'readonly',
            },
        },
    },
    {
        files: ['scripts/**/*.js', 'babel.config.js', 'tests/js/__mocks__/**/*.js'],
        languageOptions: {
            sourceType: 'commonjs',
            globals: {
                require: 'readonly',
                module: 'readonly',
                __dirname: 'readonly',
                process: 'readonly',
                exports: 'readonly',
            },
        },
        rules: {
            'no-console': 'off',
        },
    },
];
