[tool.mypy]
mypy_path = "typings"
warn_unused_ignores = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "yfinance.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "polygon.*"
ignore_missing_imports = true
