name: Composition Data Refresh

on:
    schedule:
        - cron: '0 10 * * *'
    workflow_dispatch:

jobs:
    refresh:
        runs-on: ubuntu-latest
        env:
            PYTHON_VERSION: '3.11'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-dev.txt
                  pip install pandas

            - name: Run composition data generation
              run: |
                  python scripts/generate_composition_data.py

            - name: Commit outputs if changed
              run: |
                  git config user.name 'github-actions'
                  git config user.email 'github-actions@github.com'
                  git add data/output/figures/composition.json
                  if git diff --cached --quiet; then
                    echo 'No changes to commit.'
                  else
                    git commit -m "Automated composition data refresh"
                    git push
                  fi
