export const chartLayouts = {
    performance: null,
    contribution: null,
    composition: null,
    compositionAbs: null,
    concentration: null,
    pe: null,
    fx: null,
    sectors: null,
    sectorsAbs: null,
    drawdown: null,
    drawdownAbs: null,
    rolling: null,
    volatility: null,
    beta: null,
};
